package com.jike.business.dao;

import com.jike.business.model.BoBiddingResult;

public interface BoBiddingResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	int deleteByPrimaryKey(Long biddingResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	int insert(BoBiddingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	int insertSelective(BoBiddingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	BoBiddingResult selectByPrimaryKey(Long biddingResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	int updateByPrimaryKeySelective(BoBiddingResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_bidding_result
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	int updateByPrimaryKey(BoBiddingResult record);
}