package com.jike.business.dao;

import com.jike.business.model.BoBidding;

public interface BoBiddingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    int deleteByPrimaryKey(Long biddingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    int insert(BoBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    int insertSelective(BoBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    BoBidding selectByPrimaryKey(Long biddingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    int updateByPrimaryKeySelective(BoBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_bidding
     *
     * @mbggenerated Mon Apr 10 16:27:34 CST 2017
     */
    int updateByPrimaryKey(BoBidding record);
}