package com.jike.business.dao;

import com.jike.business.model.BoFeeDetail;

public interface BoFeeDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	int deleteByPrimaryKey(Long detailFeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	int insert(BoFeeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	int insertSelective(BoFeeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	BoFeeDetail selectByPrimaryKey(Long detailFeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	int updateByPrimaryKeySelective(BoFeeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_fee_detail
	 * @mbggenerated  Thu Apr 06 18:05:34 CST 2017
	 */
	int updateByPrimaryKey(BoFeeDetail record);
}