package com.jike.business.dao;

import com.jike.business.model.BoInTrial;

public interface BoInTrialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    int deleteByPrimaryKey(Long inTrialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    int insert(BoInTrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    int insertSelective(BoInTrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    BoInTrial selectByPrimaryKey(Long inTrialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    int updateByPrimaryKeySelective(BoInTrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_in_trial
     *
     * @mbggenerated Mon Apr 10 15:26:29 CST 2017
     */
    int updateByPrimaryKey(BoInTrial record);

    /**
     * 通过日志ID查询试用
     * @param logId
     * @return
     * @created wangyb
     * @createtime 2017年4月11日下午7:26:20
     */
	BoInTrial selectInTrialByLogId(Long logId);
}