package com.jike.business.dao;

import com.jike.business.model.BoInformationCollect;

public interface BoInformationCollectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	int deleteByPrimaryKey(Long boInformationCollectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	int insert(BoInformationCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	int insertSelective(BoInformationCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	BoInformationCollect selectByPrimaryKey(Long boInformationCollectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	int updateByPrimaryKeySelective(BoInformationCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_information_collect
	 * @mbggenerated  Wed Apr 12 18:19:14 CST 2017
	 */
	int updateByPrimaryKey(BoInformationCollect record);

	/**
	 * 通过商机ID查询信息收集
	 * @param businessOpportunityId
	 * @return
	 * @created wangyb
	 * @createtime 2017年4月7日下午4:08:08
	 */
	BoInformationCollect selectByBusinessOpportunityId(Long businessOpportunityId);

	/**
	 * 通过logId删除信息收集
	 * @param logId
	 * @created wangyb
	 * @createtime 2017年4月11日下午3:23:11
	 */
	void deleteByBusinessOpportunityId(Long businessOpportunityId);
}