package com.jike.business.dao;

import java.util.List;

import com.jike.business.model.BoNegotiation;
import com.jike.business.model.BoVisitPlan;

public interface BoNegotiationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	int deleteByPrimaryKey(Long negotiationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	int insert(BoNegotiation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	int insertSelective(BoNegotiation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	BoNegotiation selectByPrimaryKey(Long negotiationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	int updateByPrimaryKeySelective(BoNegotiation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_negotiation
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	int updateByPrimaryKey(BoNegotiation record);

    /**
     * 查询该商机谈判次数
     * @param businessOpportunityId
     * @return
     * @created wangyb
     * @createtime 2017年4月10日下午2:07:55
     */
	List<BoVisitPlan> selecNegotiationByBusinessOpportunityId(Long businessOpportunityId);

	/**
	 * 通过日志ID查询谈判
	 * @param logId
	 * @return
	 * @created wangyb
	 * @createtime 2017年4月11日下午7:20:26
	 */
	BoNegotiation selectNegotiationByLogId(Long logId);
}