package com.jike.business.dao;

import com.jike.business.model.BoPayment;

public interface BoPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    int deleteByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    int insert(BoPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    int insertSelective(BoPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    BoPayment selectByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    int updateByPrimaryKeySelective(BoPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_payment
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    int updateByPrimaryKey(BoPayment record);

	BoPayment selectBoPaymentByLogId(Long logId);
}