package com.jike.business.dao;

import org.apache.ibatis.annotations.Param;

import com.jike.business.model.BoProcessHistory;

public interface BoProcessHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    int deleteByPrimaryKey(Long boProcessHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    int insert(BoProcessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    int insertSelective(BoProcessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    BoProcessHistory selectByPrimaryKey(Long boProcessHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    int updateByPrimaryKeySelective(BoProcessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_process_history
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    int updateByPrimaryKey(BoProcessHistory record);

	BoProcessHistory selectByBoIdAndBoProcess(@Param("businessOpportunityId")Long businessOpportunityId, @Param("businessOpportunityProcess")String businessOpportunityProcess);
}