package com.jike.business.dao;

import com.jike.business.model.BoPurchase;

public interface BoPurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    int deleteByPrimaryKey(Long purchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    int insert(BoPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    int insertSelective(BoPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    BoPurchase selectByPrimaryKey(Long purchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    int updateByPrimaryKeySelective(BoPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_purchase
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    int updateByPrimaryKey(BoPurchase record);

	BoPurchase selectBoPurchaseByLogId(Long logId);
}