package com.jike.business.dao;

import com.jike.business.model.BoSign;

public interface BoSignMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	int deleteByPrimaryKey(Long signId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	int insert(BoSign record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	int insertSelective(BoSign record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	BoSign selectByPrimaryKey(Long signId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	int updateByPrimaryKeySelective(BoSign record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_sign
	 * @mbggenerated  Thu Apr 13 10:14:44 CST 2017
	 */
	int updateByPrimaryKey(BoSign record);

	BoSign selectBoSignByLogId(Long logId);
}