package com.jike.business.dao;

import com.jike.business.model.BoSupport;

public interface BoSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    int deleteByPrimaryKey(Long boSupportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    int insert(BoSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    int insertSelective(BoSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    BoSupport selectByPrimaryKey(Long boSupportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    int updateByPrimaryKeySelective(BoSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bo_support
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    int updateByPrimaryKey(BoSupport record);
}