package com.jike.business.dao;

import com.jike.business.model.BoVisitPlan;

public interface BoVisitPlanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int deleteByPrimaryKey(Long visitPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int insert(BoVisitPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int insertSelective(BoVisitPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	BoVisitPlan selectByPrimaryKey(Long visitPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int updateByPrimaryKeySelective(BoVisitPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit_plan
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int updateByPrimaryKey(BoVisitPlan record);
}