package com.jike.business.dao;

import com.jike.business.model.BoVisit;

public interface BoVisitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	int deleteByPrimaryKey(Long visitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	int insert(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	int insertSelective(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	BoVisit selectByPrimaryKey(Long visitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	int updateByPrimaryKeySelective(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Tue Apr 11 19:14:47 CST 2017
	 */
	int updateByPrimaryKey(BoVisit record);

	/**
	 * 通过日志ID查询拜访
	 * @param logId
	 * @return
	 * @created wangyb
	 * @createtime 2017年4月11日下午7:15:02
	 */
	BoVisit selectVisitByLogId(Long logId);
}