package com.jike.business.dao;

import com.jike.business.model.BoVisit;

public interface BoVisitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int deleteByPrimaryKey(Long visitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int insert(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int insertSelective(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	BoVisit selectByPrimaryKey(Long visitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int updateByPrimaryKeySelective(BoVisit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bo_visit
	 * @mbggenerated  Fri Apr 07 15:17:00 CST 2017
	 */
	int updateByPrimaryKey(BoVisit record);
}