package com.jike.business.dao;

import com.jike.business.model.BusinessOpportunityLog;

public interface BusinessOpportunityLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	int deleteByPrimaryKey(Long logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	int insert(BusinessOpportunityLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	int insertSelective(BusinessOpportunityLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	BusinessOpportunityLog selectByPrimaryKey(Long logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	int updateByPrimaryKeySelective(BusinessOpportunityLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table business_opportunity_log
	 * @mbggenerated  Thu Apr 06 18:05:05 CST 2017
	 */
	int updateByPrimaryKey(BusinessOpportunityLog record);
}