package com.jike.business.dao;

import org.apache.ibatis.annotations.Param;

import com.jike.business.model.BusinessOpportunity;

public interface BusinessOpportunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    int deleteByPrimaryKey(Long businessOpportunityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    int insert(BusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    int insertSelective(BusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    BusinessOpportunity selectByPrimaryKey(Long businessOpportunityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    int updateByPrimaryKeySelective(BusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_opportunity
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    int updateByPrimaryKey(BusinessOpportunity record);

    /**
     * 通过商机流水号查询查询商机
     * @param businessOpportunityNum
     * @return
     * @created wangyb
     * @createtime 2017年4月5日下午4:14:49
     */
	BusinessOpportunity selectByBusinessOpportunityNum(@Param("businessOpportunityNum")String businessOpportunityNum);
}