package com.jike.business.dao;

import com.jike.business.model.CooperativePartnerSchool;

public interface CooperativePartnerSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    int deleteByPrimaryKey(Long cooperativePartnerSchoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    int insert(CooperativePartnerSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    int insertSelective(CooperativePartnerSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    CooperativePartnerSchool selectByPrimaryKey(Long cooperativePartnerSchoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    int updateByPrimaryKeySelective(CooperativePartnerSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_school
     *
     * @mbggenerated Wed May 10 18:09:32 CST 2017
     */
    int updateByPrimaryKey(CooperativePartnerSchool record);
    /**
     * 查询该学校所在的合作伙伴分配者
     * @param cooperativePartnerSchoolId
     * @return
     * @created wangyb
     * @createtime 2017年5月12日下午3:18:17
     */
    Long selectDistributeIdByCpsId(Long cooperativePartnerSchoolId);
}