package com.jike.business.dao;

import java.util.List;

import com.jike.business.model.ServiceBusinessOpportunity;

public interface ServiceBusinessOpportunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    int deleteByPrimaryKey(Long serviceBusinessOpportunityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    int insert(ServiceBusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    int insertSelective(ServiceBusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    ServiceBusinessOpportunity selectByPrimaryKey(Long serviceBusinessOpportunityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceBusinessOpportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_business_opportunity
     *
     * @mbggenerated Thu Apr 13 11:55:27 CST 2017
     */
    int updateByPrimaryKey(ServiceBusinessOpportunity record);

    /**
     * 查询该商机分配的服务
     * @param businessOpportunityId
     * @return
     * @created wangyb
     * @createtime 2017年4月13日下午2:17:09
     */
	List<ServiceBusinessOpportunity> selectByBusinessOpportunityId(Long businessOpportunityId);
}