package com.jike.business.dao;

import com.jike.business.model.ServiceDailyEvent;

public interface ServiceDailyEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    int deleteByPrimaryKey(Long seviceDailyEventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    int insert(ServiceDailyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    int insertSelective(ServiceDailyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    ServiceDailyEvent selectByPrimaryKey(Long seviceDailyEventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceDailyEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_daily_event
     *
     * @mbggenerated Mon Apr 24 10:10:32 CST 2017
     */
    int updateByPrimaryKey(ServiceDailyEvent record);

	ServiceDailyEvent selectByLogId(Long logId);
}