package com.jike.user.model;

import java.util.Date;

public class BoEventLabel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long boEventLabelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.eveid
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Integer eveid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.evename
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private String evename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.patent_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Integer patentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.update_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_event_label.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.bo_event_label_id
	 * @return  the value of bo_event_label.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getBoEventLabelId() {
		return boEventLabelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.bo_event_label_id
	 * @param boEventLabelId  the value for bo_event_label.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setBoEventLabelId(Long boEventLabelId) {
		this.boEventLabelId = boEventLabelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.eveid
	 * @return  the value of bo_event_label.eveid
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Integer getEveid() {
		return eveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.eveid
	 * @param eveid  the value for bo_event_label.eveid
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setEveid(Integer eveid) {
		this.eveid = eveid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.evename
	 * @return  the value of bo_event_label.evename
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public String getEvename() {
		return evename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.evename
	 * @param evename  the value for bo_event_label.evename
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setEvename(String evename) {
		this.evename = evename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.patent_id
	 * @return  the value of bo_event_label.patent_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Integer getPatentId() {
		return patentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.patent_id
	 * @param patentId  the value for bo_event_label.patent_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setPatentId(Integer patentId) {
		this.patentId = patentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.create_by
	 * @return  the value of bo_event_label.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.create_by
	 * @param createBy  the value for bo_event_label.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.create_time
	 * @return  the value of bo_event_label.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.create_time
	 * @param createTime  the value for bo_event_label.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.update_by
	 * @return  the value of bo_event_label.update_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.update_by
	 * @param updateBy  the value for bo_event_label.update_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_event_label.update_time
	 * @return  the value of bo_event_label.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_event_label.update_time
	 * @param updateTime  the value for bo_event_label.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}