package com.jike.user.model;

import java.util.Date;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.permission_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String permissionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.parent_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.description
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.sort
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.permission_id
	 * @return  the value of permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.permission_id
	 * @param permissionId  the value for permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.permission_name
	 * @return  the value of permission.permission_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getPermissionName() {
		return permissionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.permission_name
	 * @param permissionName  the value for permission.permission_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.parent_id
	 * @return  the value of permission.parent_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.parent_id
	 * @param parentId  the value for permission.parent_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.description
	 * @return  the value of permission.description
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.description
	 * @param description  the value for permission.description
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.sort
	 * @return  the value of permission.sort
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.sort
	 * @param sort  the value for permission.sort
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.create_time
	 * @return  the value of permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.create_time
	 * @param createTime  the value for permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.update_time
	 * @return  the value of permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.update_time
	 * @param updateTime  the value for permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}