package com.jike.user.model;

import java.util.Date;

public class RoleEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.role_event_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long roleEventId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.role_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long boEventLabelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.udpate_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Long udpateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_event.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.role_event_id
	 * @return  the value of role_event.role_event_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getRoleEventId() {
		return roleEventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.role_event_id
	 * @param roleEventId  the value for role_event.role_event_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setRoleEventId(Long roleEventId) {
		this.roleEventId = roleEventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.role_id
	 * @return  the value of role_event.role_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.role_id
	 * @param roleId  the value for role_event.role_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.bo_event_label_id
	 * @return  the value of role_event.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getBoEventLabelId() {
		return boEventLabelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.bo_event_label_id
	 * @param boEventLabelId  the value for role_event.bo_event_label_id
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setBoEventLabelId(Long boEventLabelId) {
		this.boEventLabelId = boEventLabelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.create_by
	 * @return  the value of role_event.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.create_by
	 * @param createBy  the value for role_event.create_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.create_time
	 * @return  the value of role_event.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.create_time
	 * @param createTime  the value for role_event.create_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.udpate_by
	 * @return  the value of role_event.udpate_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Long getUdpateBy() {
		return udpateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.udpate_by
	 * @param udpateBy  the value for role_event.udpate_by
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setUdpateBy(Long udpateBy) {
		this.udpateBy = udpateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_event.update_time
	 * @return  the value of role_event.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_event.update_time
	 * @param updateTime  the value for role_event.update_time
	 * @mbggenerated  Mon Apr 17 16:45:27 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}