package com.jike.user.model;

import java.util.Date;

public class RolePermission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.role_permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long rolePermissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.role_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.permission_type
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Integer permissionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.role_permission_id
	 * @return  the value of role_permission.role_permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getRolePermissionId() {
		return rolePermissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.role_permission_id
	 * @param rolePermissionId  the value for role_permission.role_permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setRolePermissionId(Long rolePermissionId) {
		this.rolePermissionId = rolePermissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.role_id
	 * @return  the value of role_permission.role_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.role_id
	 * @param roleId  the value for role_permission.role_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.permission_id
	 * @return  the value of role_permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.permission_id
	 * @param permissionId  the value for role_permission.permission_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.permission_type
	 * @return  the value of role_permission.permission_type
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Integer getPermissionType() {
		return permissionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.permission_type
	 * @param permissionType  the value for role_permission.permission_type
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPermissionType(Integer permissionType) {
		this.permissionType = permissionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.create_time
	 * @return  the value of role_permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.create_time
	 * @param createTime  the value for role_permission.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.update_time
	 * @return  the value of role_permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.update_time
	 * @param updateTime  the value for role_permission.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}