package com.jike.user.model;

import java.util.Date;

public class SalesLeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.sales_leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Long salesLeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Long leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.managed_user_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Long managedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.create_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.create_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.update_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leader.update_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.sales_leader_id
     *
     * @return the value of sales_leader.sales_leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Long getSalesLeaderId() {
        return salesLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.sales_leader_id
     *
     * @param salesLeaderId the value for sales_leader.sales_leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setSalesLeaderId(Long salesLeaderId) {
        this.salesLeaderId = salesLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.leader_id
     *
     * @return the value of sales_leader.leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Long getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.leader_id
     *
     * @param leaderId the value for sales_leader.leader_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setLeaderId(Long leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.managed_user_id
     *
     * @return the value of sales_leader.managed_user_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Long getManagedUserId() {
        return managedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.managed_user_id
     *
     * @param managedUserId the value for sales_leader.managed_user_id
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setManagedUserId(Long managedUserId) {
        this.managedUserId = managedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.create_by
     *
     * @return the value of sales_leader.create_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.create_by
     *
     * @param createBy the value for sales_leader.create_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.create_time
     *
     * @return the value of sales_leader.create_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.create_time
     *
     * @param createTime the value for sales_leader.create_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.update_by
     *
     * @return the value of sales_leader.update_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.update_by
     *
     * @param updateBy the value for sales_leader.update_by
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leader.update_time
     *
     * @return the value of sales_leader.update_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leader.update_time
     *
     * @param updateTime the value for sales_leader.update_time
     *
     * @mbggenerated Mon Apr 17 17:56:28 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}