package com.jike.user.model;

import java.util.Date;

public class ServiceLeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.service_leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Long serviceLeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Long leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.managed_user_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Long managedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.create_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.create_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.update_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_leader.update_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.service_leader_id
     *
     * @return the value of service_leader.service_leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Long getServiceLeaderId() {
        return serviceLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.service_leader_id
     *
     * @param serviceLeaderId the value for service_leader.service_leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setServiceLeaderId(Long serviceLeaderId) {
        this.serviceLeaderId = serviceLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.leader_id
     *
     * @return the value of service_leader.leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Long getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.leader_id
     *
     * @param leaderId the value for service_leader.leader_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setLeaderId(Long leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.managed_user_id
     *
     * @return the value of service_leader.managed_user_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Long getManagedUserId() {
        return managedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.managed_user_id
     *
     * @param managedUserId the value for service_leader.managed_user_id
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setManagedUserId(Long managedUserId) {
        this.managedUserId = managedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.create_by
     *
     * @return the value of service_leader.create_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.create_by
     *
     * @param createBy the value for service_leader.create_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.create_time
     *
     * @return the value of service_leader.create_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.create_time
     *
     * @param createTime the value for service_leader.create_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.update_by
     *
     * @return the value of service_leader.update_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.update_by
     *
     * @param updateBy the value for service_leader.update_by
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_leader.update_time
     *
     * @return the value of service_leader.update_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_leader.update_time
     *
     * @param updateTime the value for service_leader.update_time
     *
     * @mbggenerated Thu May 18 17:18:28 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}