package com.jike.user.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.login_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.employee_num
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private String employeeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.is_employment
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Integer isEmployment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.entry_date
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date entryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.login_name
	 * @return  the value of user.login_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.login_name
	 * @param loginName  the value for user.login_name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.employee_num
	 * @return  the value of user.employee_num
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public String getEmployeeNum() {
		return employeeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.employee_num
	 * @param employeeNum  the value for user.employee_num
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setEmployeeNum(String employeeNum) {
		this.employeeNum = employeeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.is_employment
	 * @return  the value of user.is_employment
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Integer getIsEmployment() {
		return isEmployment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.is_employment
	 * @param isEmployment  the value for user.is_employment
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setIsEmployment(Integer isEmployment) {
		this.isEmployment = isEmployment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.entry_date
	 * @return  the value of user.entry_date
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getEntryDate() {
		return entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.entry_date
	 * @param entryDate  the value for user.entry_date
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_time
	 * @return  the value of user.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_time
	 * @param updateTime  the value for user.update_time
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}