package com.jike.user.dao;

import com.jike.user.model.Permission;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int deleteByPrimaryKey(Long permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	Permission selectByPrimaryKey(Long permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int updateByPrimaryKey(Permission record);
}