package com.jike.user.dao;

import com.jike.user.model.Permission;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	int deleteByPrimaryKey(Long permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	Permission selectByPrimaryKey(Long permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Tue Mar 28 08:44:37 CST 2017
	 */
	int updateByPrimaryKey(Permission record);

	/**
	 * 通过权限名称查询权限信息
	 * @param permissionName
	 * @return
	 * @created wangyb
	 * @createtime 2017年3月28日上午11:58:06
	 */
	Permission selectByPermissionName(String permissionName);
}