package com.jike.user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jike.user.model.Permission;
import com.jike.user.model.RolePermission;

public interface RolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int deleteByPrimaryKey(Long rolePermissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int insert(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int insertSelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	RolePermission selectByPrimaryKey(Long rolePermissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int updateByPrimaryKeySelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbggenerated  Mon Mar 27 17:49:49 CST 2017
	 */
	int updateByPrimaryKey(RolePermission record);
}