package com.jike.business.model;

import java.util.Date;

public class BoBiddingResult {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.bidding_result_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Long biddingResultId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.log_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Long logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.business_opportunity_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Long businessOpportunityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.bidding_result_detail
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private String biddingResultDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.create_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.create_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.update_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_bidding_result.update_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	private Long updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.bidding_result_id
	 * @return  the value of bo_bidding_result.bidding_result_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Long getBiddingResultId() {
		return biddingResultId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.bidding_result_id
	 * @param biddingResultId  the value for bo_bidding_result.bidding_result_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setBiddingResultId(Long biddingResultId) {
		this.biddingResultId = biddingResultId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.log_id
	 * @return  the value of bo_bidding_result.log_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Long getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.log_id
	 * @param logId  the value for bo_bidding_result.log_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setLogId(Long logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.business_opportunity_id
	 * @return  the value of bo_bidding_result.business_opportunity_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Long getBusinessOpportunityId() {
		return businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.business_opportunity_id
	 * @param businessOpportunityId  the value for bo_bidding_result.business_opportunity_id
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setBusinessOpportunityId(Long businessOpportunityId) {
		this.businessOpportunityId = businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.bidding_result_detail
	 * @return  the value of bo_bidding_result.bidding_result_detail
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public String getBiddingResultDetail() {
		return biddingResultDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.bidding_result_detail
	 * @param biddingResultDetail  the value for bo_bidding_result.bidding_result_detail
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setBiddingResultDetail(String biddingResultDetail) {
		this.biddingResultDetail = biddingResultDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.create_time
	 * @return  the value of bo_bidding_result.create_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.create_time
	 * @param createTime  the value for bo_bidding_result.create_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.create_by
	 * @return  the value of bo_bidding_result.create_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.create_by
	 * @param createBy  the value for bo_bidding_result.create_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.update_time
	 * @return  the value of bo_bidding_result.update_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.update_time
	 * @param updateTime  the value for bo_bidding_result.update_time
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_bidding_result.update_by
	 * @return  the value of bo_bidding_result.update_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_bidding_result.update_by
	 * @param updateBy  the value for bo_bidding_result.update_by
	 * @mbggenerated  Tue Apr 11 19:30:49 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}
}