package com.jike.business.model;

import java.util.Date;

public class BoInformationCollect {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.bo_information_collect_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Long boInformationCollectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.business_opportunity_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Long businessOpportunityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.information_sources
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String informationSources;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.school_scale
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String schoolScale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.school_level
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String schoolLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.school_property
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Integer schoolProperty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.school_type
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String schoolType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactLandline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactQq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.contact_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String contactWechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerLandline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerQq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.decision_maker_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private String decisionMakerWechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.if_Intention
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Integer ifIntention;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.if_interested
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Integer ifInterested;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.create_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.create_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.update_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_information_collect.update_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	private Long updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.bo_information_collect_id
	 * @return  the value of bo_information_collect.bo_information_collect_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Long getBoInformationCollectId() {
		return boInformationCollectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.bo_information_collect_id
	 * @param boInformationCollectId  the value for bo_information_collect.bo_information_collect_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setBoInformationCollectId(Long boInformationCollectId) {
		this.boInformationCollectId = boInformationCollectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.business_opportunity_id
	 * @return  the value of bo_information_collect.business_opportunity_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Long getBusinessOpportunityId() {
		return businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.business_opportunity_id
	 * @param businessOpportunityId  the value for bo_information_collect.business_opportunity_id
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setBusinessOpportunityId(Long businessOpportunityId) {
		this.businessOpportunityId = businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.information_sources
	 * @return  the value of bo_information_collect.information_sources
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getInformationSources() {
		return informationSources;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.information_sources
	 * @param informationSources  the value for bo_information_collect.information_sources
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setInformationSources(String informationSources) {
		this.informationSources = informationSources;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.school_scale
	 * @return  the value of bo_information_collect.school_scale
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getSchoolScale() {
		return schoolScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.school_scale
	 * @param schoolScale  the value for bo_information_collect.school_scale
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setSchoolScale(String schoolScale) {
		this.schoolScale = schoolScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.school_level
	 * @return  the value of bo_information_collect.school_level
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getSchoolLevel() {
		return schoolLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.school_level
	 * @param schoolLevel  the value for bo_information_collect.school_level
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setSchoolLevel(String schoolLevel) {
		this.schoolLevel = schoolLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.school_property
	 * @return  the value of bo_information_collect.school_property
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Integer getSchoolProperty() {
		return schoolProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.school_property
	 * @param schoolProperty  the value for bo_information_collect.school_property
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setSchoolProperty(Integer schoolProperty) {
		this.schoolProperty = schoolProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.school_type
	 * @return  the value of bo_information_collect.school_type
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getSchoolType() {
		return schoolType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.school_type
	 * @param schoolType  the value for bo_information_collect.school_type
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setSchoolType(String schoolType) {
		this.schoolType = schoolType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_name
	 * @return  the value of bo_information_collect.contact_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_name
	 * @param contactName  the value for bo_information_collect.contact_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_title
	 * @return  the value of bo_information_collect.contact_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactTitle() {
		return contactTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_title
	 * @param contactTitle  the value for bo_information_collect.contact_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactTitle(String contactTitle) {
		this.contactTitle = contactTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_landline
	 * @return  the value of bo_information_collect.contact_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactLandline() {
		return contactLandline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_landline
	 * @param contactLandline  the value for bo_information_collect.contact_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactLandline(String contactLandline) {
		this.contactLandline = contactLandline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_phone
	 * @return  the value of bo_information_collect.contact_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_phone
	 * @param contactPhone  the value for bo_information_collect.contact_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_email
	 * @return  the value of bo_information_collect.contact_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactEmail() {
		return contactEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_email
	 * @param contactEmail  the value for bo_information_collect.contact_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_qq
	 * @return  the value of bo_information_collect.contact_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactQq() {
		return contactQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_qq
	 * @param contactQq  the value for bo_information_collect.contact_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactQq(String contactQq) {
		this.contactQq = contactQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.contact_wechat
	 * @return  the value of bo_information_collect.contact_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getContactWechat() {
		return contactWechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.contact_wechat
	 * @param contactWechat  the value for bo_information_collect.contact_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setContactWechat(String contactWechat) {
		this.contactWechat = contactWechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_name
	 * @return  the value of bo_information_collect.decision_maker_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerName() {
		return decisionMakerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_name
	 * @param decisionMakerName  the value for bo_information_collect.decision_maker_name
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerName(String decisionMakerName) {
		this.decisionMakerName = decisionMakerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_title
	 * @return  the value of bo_information_collect.decision_maker_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerTitle() {
		return decisionMakerTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_title
	 * @param decisionMakerTitle  the value for bo_information_collect.decision_maker_title
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerTitle(String decisionMakerTitle) {
		this.decisionMakerTitle = decisionMakerTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_landline
	 * @return  the value of bo_information_collect.decision_maker_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerLandline() {
		return decisionMakerLandline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_landline
	 * @param decisionMakerLandline  the value for bo_information_collect.decision_maker_landline
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerLandline(String decisionMakerLandline) {
		this.decisionMakerLandline = decisionMakerLandline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_phone
	 * @return  the value of bo_information_collect.decision_maker_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerPhone() {
		return decisionMakerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_phone
	 * @param decisionMakerPhone  the value for bo_information_collect.decision_maker_phone
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerPhone(String decisionMakerPhone) {
		this.decisionMakerPhone = decisionMakerPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_email
	 * @return  the value of bo_information_collect.decision_maker_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerEmail() {
		return decisionMakerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_email
	 * @param decisionMakerEmail  the value for bo_information_collect.decision_maker_email
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerEmail(String decisionMakerEmail) {
		this.decisionMakerEmail = decisionMakerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_qq
	 * @return  the value of bo_information_collect.decision_maker_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerQq() {
		return decisionMakerQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_qq
	 * @param decisionMakerQq  the value for bo_information_collect.decision_maker_qq
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerQq(String decisionMakerQq) {
		this.decisionMakerQq = decisionMakerQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.decision_maker_wechat
	 * @return  the value of bo_information_collect.decision_maker_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public String getDecisionMakerWechat() {
		return decisionMakerWechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.decision_maker_wechat
	 * @param decisionMakerWechat  the value for bo_information_collect.decision_maker_wechat
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setDecisionMakerWechat(String decisionMakerWechat) {
		this.decisionMakerWechat = decisionMakerWechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.if_Intention
	 * @return  the value of bo_information_collect.if_Intention
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Integer getIfIntention() {
		return ifIntention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.if_Intention
	 * @param ifIntention  the value for bo_information_collect.if_Intention
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setIfIntention(Integer ifIntention) {
		this.ifIntention = ifIntention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.if_interested
	 * @return  the value of bo_information_collect.if_interested
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Integer getIfInterested() {
		return ifInterested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.if_interested
	 * @param ifInterested  the value for bo_information_collect.if_interested
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setIfInterested(Integer ifInterested) {
		this.ifInterested = ifInterested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.create_time
	 * @return  the value of bo_information_collect.create_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.create_time
	 * @param createTime  the value for bo_information_collect.create_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.create_by
	 * @return  the value of bo_information_collect.create_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.create_by
	 * @param createBy  the value for bo_information_collect.create_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.update_time
	 * @return  the value of bo_information_collect.update_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.update_time
	 * @param updateTime  the value for bo_information_collect.update_time
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_information_collect.update_by
	 * @return  the value of bo_information_collect.update_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_information_collect.update_by
	 * @param updateBy  the value for bo_information_collect.update_by
	 * @mbggenerated  Fri Apr 07 09:29:54 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}
}