package com.jike.business.model;

import java.util.Date;

public class BoNegotiation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.negotiation_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Long negotiationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.business_opportunity_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Long businessOpportunityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.log_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Long logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.negotiation_name
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private String negotiationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.negotiation_detail
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private String negotiationDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.create_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.create_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.update_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_negotiation.update_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	private Long updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.negotiation_id
	 * @return  the value of bo_negotiation.negotiation_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Long getNegotiationId() {
		return negotiationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.negotiation_id
	 * @param negotiationId  the value for bo_negotiation.negotiation_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setNegotiationId(Long negotiationId) {
		this.negotiationId = negotiationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.business_opportunity_id
	 * @return  the value of bo_negotiation.business_opportunity_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Long getBusinessOpportunityId() {
		return businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.business_opportunity_id
	 * @param businessOpportunityId  the value for bo_negotiation.business_opportunity_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setBusinessOpportunityId(Long businessOpportunityId) {
		this.businessOpportunityId = businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.log_id
	 * @return  the value of bo_negotiation.log_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Long getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.log_id
	 * @param logId  the value for bo_negotiation.log_id
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setLogId(Long logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.negotiation_name
	 * @return  the value of bo_negotiation.negotiation_name
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public String getNegotiationName() {
		return negotiationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.negotiation_name
	 * @param negotiationName  the value for bo_negotiation.negotiation_name
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setNegotiationName(String negotiationName) {
		this.negotiationName = negotiationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.negotiation_detail
	 * @return  the value of bo_negotiation.negotiation_detail
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public String getNegotiationDetail() {
		return negotiationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.negotiation_detail
	 * @param negotiationDetail  the value for bo_negotiation.negotiation_detail
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setNegotiationDetail(String negotiationDetail) {
		this.negotiationDetail = negotiationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.create_time
	 * @return  the value of bo_negotiation.create_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.create_time
	 * @param createTime  the value for bo_negotiation.create_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.create_by
	 * @return  the value of bo_negotiation.create_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.create_by
	 * @param createBy  the value for bo_negotiation.create_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.update_time
	 * @return  the value of bo_negotiation.update_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.update_time
	 * @param updateTime  the value for bo_negotiation.update_time
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_negotiation.update_by
	 * @return  the value of bo_negotiation.update_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_negotiation.update_by
	 * @param updateBy  the value for bo_negotiation.update_by
	 * @mbggenerated  Mon Apr 10 14:09:33 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}
}