package com.jike.business.model;

import java.math.BigDecimal;
import java.util.Date;

public class BoPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.payment_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Long paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.business_opportunity_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.log_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.payment_date
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Date paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.payment_amount
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private BigDecimal paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.payment_type
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.create_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.create_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.update_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_payment.update_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.payment_id
     *
     * @return the value of bo_payment.payment_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.payment_id
     *
     * @param paymentId the value for bo_payment.payment_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.business_opportunity_id
     *
     * @return the value of bo_payment.business_opportunity_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_payment.business_opportunity_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.log_id
     *
     * @return the value of bo_payment.log_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.log_id
     *
     * @param logId the value for bo_payment.log_id
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.payment_date
     *
     * @return the value of bo_payment.payment_date
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.payment_date
     *
     * @param paymentDate the value for bo_payment.payment_date
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.payment_amount
     *
     * @return the value of bo_payment.payment_amount
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public BigDecimal getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.payment_amount
     *
     * @param paymentAmount the value for bo_payment.payment_amount
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.payment_type
     *
     * @return the value of bo_payment.payment_type
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.payment_type
     *
     * @param paymentType the value for bo_payment.payment_type
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.create_by
     *
     * @return the value of bo_payment.create_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.create_by
     *
     * @param createBy the value for bo_payment.create_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.create_time
     *
     * @return the value of bo_payment.create_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.create_time
     *
     * @param createTime the value for bo_payment.create_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.update_by
     *
     * @return the value of bo_payment.update_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.update_by
     *
     * @param updateBy the value for bo_payment.update_by
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_payment.update_time
     *
     * @return the value of bo_payment.update_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_payment.update_time
     *
     * @param updateTime the value for bo_payment.update_time
     *
     * @mbggenerated Mon Apr 17 10:09:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}