package com.jike.business.model;

import java.util.Date;

public class BoProcessHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.bo_process_history_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Long boProcessHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.business_opportunity_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.log_date
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.business_opportunity_process
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private String businessOpportunityProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.create_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.create_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.update_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_process_history.update_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.bo_process_history_id
     *
     * @return the value of bo_process_history.bo_process_history_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Long getBoProcessHistoryId() {
        return boProcessHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.bo_process_history_id
     *
     * @param boProcessHistoryId the value for bo_process_history.bo_process_history_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setBoProcessHistoryId(Long boProcessHistoryId) {
        this.boProcessHistoryId = boProcessHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.business_opportunity_id
     *
     * @return the value of bo_process_history.business_opportunity_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_process_history.business_opportunity_id
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.log_date
     *
     * @return the value of bo_process_history.log_date
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.log_date
     *
     * @param logDate the value for bo_process_history.log_date
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.business_opportunity_process
     *
     * @return the value of bo_process_history.business_opportunity_process
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public String getBusinessOpportunityProcess() {
        return businessOpportunityProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.business_opportunity_process
     *
     * @param businessOpportunityProcess the value for bo_process_history.business_opportunity_process
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setBusinessOpportunityProcess(String businessOpportunityProcess) {
        this.businessOpportunityProcess = businessOpportunityProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.create_by
     *
     * @return the value of bo_process_history.create_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.create_by
     *
     * @param createBy the value for bo_process_history.create_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.create_time
     *
     * @return the value of bo_process_history.create_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.create_time
     *
     * @param createTime the value for bo_process_history.create_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.update_by
     *
     * @return the value of bo_process_history.update_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.update_by
     *
     * @param updateBy the value for bo_process_history.update_by
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_process_history.update_time
     *
     * @return the value of bo_process_history.update_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_process_history.update_time
     *
     * @param updateTime the value for bo_process_history.update_time
     *
     * @mbggenerated Thu Apr 27 14:46:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}