package com.jike.business.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class BoPurchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.purchase_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Long purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.log_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Long businessOpportunityId;

    @JSONField (format="yyyy-MM-dd")
    private Date hardwareArrivalDate;

    @JSONField (format="yyyy-MM-dd")
    private Date softwareInstallationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.create_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.create_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.update_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_purchase.update_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.purchase_id
     *
     * @return the value of bo_purchase.purchase_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.purchase_id
     *
     * @param purchaseId the value for bo_purchase.purchase_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.log_id
     *
     * @return the value of bo_purchase.log_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.log_id
     *
     * @param logId the value for bo_purchase.log_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.business_opportunity_id
     *
     * @return the value of bo_purchase.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_purchase.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.hardware_arrival_date
     *
     * @return the value of bo_purchase.hardware_arrival_date
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Date getHardwareArrivalDate() {
        return hardwareArrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.hardware_arrival_date
     *
     * @param hardwareArrivalDate the value for bo_purchase.hardware_arrival_date
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setHardwareArrivalDate(Date hardwareArrivalDate) {
        this.hardwareArrivalDate = hardwareArrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.software_installation_date
     *
     * @return the value of bo_purchase.software_installation_date
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Date getSoftwareInstallationDate() {
        return softwareInstallationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.software_installation_date
     *
     * @param softwareInstallationDate the value for bo_purchase.software_installation_date
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setSoftwareInstallationDate(Date softwareInstallationDate) {
        this.softwareInstallationDate = softwareInstallationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.create_time
     *
     * @return the value of bo_purchase.create_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.create_time
     *
     * @param createTime the value for bo_purchase.create_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.create_by
     *
     * @return the value of bo_purchase.create_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.create_by
     *
     * @param createBy the value for bo_purchase.create_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.update_time
     *
     * @return the value of bo_purchase.update_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.update_time
     *
     * @param updateTime the value for bo_purchase.update_time
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_purchase.update_by
     *
     * @return the value of bo_purchase.update_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_purchase.update_by
     *
     * @param updateBy the value for bo_purchase.update_by
     *
     * @mbggenerated Mon Apr 10 18:28:04 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}