package com.jike.business.model;

import java.util.Date;

public class BoSupport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.bo_support_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long boSupportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.account_open_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Integer accountOpenCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.information_confirmation_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Integer informationConfirmationCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_support.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.bo_support_id
     *
     * @return the value of bo_support.bo_support_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getBoSupportId() {
        return boSupportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.bo_support_id
     *
     * @param boSupportId the value for bo_support.bo_support_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setBoSupportId(Long boSupportId) {
        this.boSupportId = boSupportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.business_opportunity_id
     *
     * @return the value of bo_support.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_support.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.log_id
     *
     * @return the value of bo_support.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.log_id
     *
     * @param logId the value for bo_support.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.account_open_count
     *
     * @return the value of bo_support.account_open_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Integer getAccountOpenCount() {
        return accountOpenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.account_open_count
     *
     * @param accountOpenCount the value for bo_support.account_open_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setAccountOpenCount(Integer accountOpenCount) {
        this.accountOpenCount = accountOpenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.information_confirmation_count
     *
     * @return the value of bo_support.information_confirmation_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Integer getInformationConfirmationCount() {
        return informationConfirmationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.information_confirmation_count
     *
     * @param informationConfirmationCount the value for bo_support.information_confirmation_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setInformationConfirmationCount(Integer informationConfirmationCount) {
        this.informationConfirmationCount = informationConfirmationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.create_by
     *
     * @return the value of bo_support.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.create_by
     *
     * @param createBy the value for bo_support.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.create_time
     *
     * @return the value of bo_support.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.create_time
     *
     * @param createTime the value for bo_support.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.update_by
     *
     * @return the value of bo_support.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.update_by
     *
     * @param updateBy the value for bo_support.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_support.update_time
     *
     * @return the value of bo_support.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_support.update_time
     *
     * @param updateTime the value for bo_support.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}