package com.jike.business.model;

import java.util.Date;
import java.math.BigDecimal;

public class BoSupport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.bo_support_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Long boSupportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.business_opportunity_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Long businessOpportunityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.log_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Long logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.account_open_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Integer accountOpenCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.information_confirmation_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Integer informationConfirmationCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.modify_student_information_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Integer modifyStudentInformationCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.sales_support_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private BigDecimal salesSupportCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.sales_support_detail
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private String salesSupportDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.product_demonstration
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Integer productDemonstration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.product_introduce
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Integer productIntroduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.create_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.create_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.update_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_support.update_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.bo_support_id
	 * @return  the value of bo_support.bo_support_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Long getBoSupportId() {
		return boSupportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.bo_support_id
	 * @param boSupportId  the value for bo_support.bo_support_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setBoSupportId(Long boSupportId) {
		this.boSupportId = boSupportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.business_opportunity_id
	 * @return  the value of bo_support.business_opportunity_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Long getBusinessOpportunityId() {
		return businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.business_opportunity_id
	 * @param businessOpportunityId  the value for bo_support.business_opportunity_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setBusinessOpportunityId(Long businessOpportunityId) {
		this.businessOpportunityId = businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.log_id
	 * @return  the value of bo_support.log_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Long getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.log_id
	 * @param logId  the value for bo_support.log_id
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setLogId(Long logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.account_open_count
	 * @return  the value of bo_support.account_open_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Integer getAccountOpenCount() {
		return accountOpenCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.account_open_count
	 * @param accountOpenCount  the value for bo_support.account_open_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setAccountOpenCount(Integer accountOpenCount) {
		this.accountOpenCount = accountOpenCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.information_confirmation_count
	 * @return  the value of bo_support.information_confirmation_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Integer getInformationConfirmationCount() {
		return informationConfirmationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.information_confirmation_count
	 * @param informationConfirmationCount  the value for bo_support.information_confirmation_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setInformationConfirmationCount(Integer informationConfirmationCount) {
		this.informationConfirmationCount = informationConfirmationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.modify_student_information_count
	 * @return  the value of bo_support.modify_student_information_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Integer getModifyStudentInformationCount() {
		return modifyStudentInformationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.modify_student_information_count
	 * @param modifyStudentInformationCount  the value for bo_support.modify_student_information_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setModifyStudentInformationCount(Integer modifyStudentInformationCount) {
		this.modifyStudentInformationCount = modifyStudentInformationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.sales_support_count
	 * @return  the value of bo_support.sales_support_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public BigDecimal getSalesSupportCount() {
		return salesSupportCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.sales_support_count
	 * @param salesSupportCount  the value for bo_support.sales_support_count
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setSalesSupportCount(BigDecimal salesSupportCount) {
		this.salesSupportCount = salesSupportCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.sales_support_detail
	 * @return  the value of bo_support.sales_support_detail
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public String getSalesSupportDetail() {
		return salesSupportDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.sales_support_detail
	 * @param salesSupportDetail  the value for bo_support.sales_support_detail
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setSalesSupportDetail(String salesSupportDetail) {
		this.salesSupportDetail = salesSupportDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.product_demonstration
	 * @return  the value of bo_support.product_demonstration
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Integer getProductDemonstration() {
		return productDemonstration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.product_demonstration
	 * @param productDemonstration  the value for bo_support.product_demonstration
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setProductDemonstration(Integer productDemonstration) {
		this.productDemonstration = productDemonstration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.product_introduce
	 * @return  the value of bo_support.product_introduce
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Integer getProductIntroduce() {
		return productIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.product_introduce
	 * @param productIntroduce  the value for bo_support.product_introduce
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setProductIntroduce(Integer productIntroduce) {
		this.productIntroduce = productIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.create_by
	 * @return  the value of bo_support.create_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.create_by
	 * @param createBy  the value for bo_support.create_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.create_time
	 * @return  the value of bo_support.create_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.create_time
	 * @param createTime  the value for bo_support.create_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.update_by
	 * @return  the value of bo_support.update_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.update_by
	 * @param updateBy  the value for bo_support.update_by
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_support.update_time
	 * @return  the value of bo_support.update_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_support.update_time
	 * @param updateTime  the value for bo_support.update_time
	 * @mbggenerated  Fri Apr 21 14:53:56 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}