package com.jike.business.model;

import java.util.Date;

public class BoTrain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.bo_train_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer boTrainId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.business_opportunity_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Long businessOpportunityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.log_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Long logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.operation_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer operationTrainingCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.correcting_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer correctingTrainingCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.ppt_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer pptDemonstratedCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.volume_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer volumeDemonstratedCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.marking_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer markingTrainCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.introduction_lean_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer introductionLeanCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.student_parent_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer studentParentIntroductionCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.examination_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer examinationTrainCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.sop_process_explanation_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer sopProcessExplanationCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.products_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer productsIntroductionCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.operation_guidance_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer operationGuidanceCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.test_coach_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Integer testCoachCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.create_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.create_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.update_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bo_train.update_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.bo_train_id
	 * @return  the value of bo_train.bo_train_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getBoTrainId() {
		return boTrainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.bo_train_id
	 * @param boTrainId  the value for bo_train.bo_train_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setBoTrainId(Integer boTrainId) {
		this.boTrainId = boTrainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.business_opportunity_id
	 * @return  the value of bo_train.business_opportunity_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Long getBusinessOpportunityId() {
		return businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.business_opportunity_id
	 * @param businessOpportunityId  the value for bo_train.business_opportunity_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setBusinessOpportunityId(Long businessOpportunityId) {
		this.businessOpportunityId = businessOpportunityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.log_id
	 * @return  the value of bo_train.log_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Long getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.log_id
	 * @param logId  the value for bo_train.log_id
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setLogId(Long logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.operation_training_count
	 * @return  the value of bo_train.operation_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getOperationTrainingCount() {
		return operationTrainingCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.operation_training_count
	 * @param operationTrainingCount  the value for bo_train.operation_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setOperationTrainingCount(Integer operationTrainingCount) {
		this.operationTrainingCount = operationTrainingCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.correcting_training_count
	 * @return  the value of bo_train.correcting_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getCorrectingTrainingCount() {
		return correctingTrainingCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.correcting_training_count
	 * @param correctingTrainingCount  the value for bo_train.correcting_training_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setCorrectingTrainingCount(Integer correctingTrainingCount) {
		this.correctingTrainingCount = correctingTrainingCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.ppt_demonstrated_count
	 * @return  the value of bo_train.ppt_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getPptDemonstratedCount() {
		return pptDemonstratedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.ppt_demonstrated_count
	 * @param pptDemonstratedCount  the value for bo_train.ppt_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setPptDemonstratedCount(Integer pptDemonstratedCount) {
		this.pptDemonstratedCount = pptDemonstratedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.volume_demonstrated_count
	 * @return  the value of bo_train.volume_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getVolumeDemonstratedCount() {
		return volumeDemonstratedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.volume_demonstrated_count
	 * @param volumeDemonstratedCount  the value for bo_train.volume_demonstrated_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setVolumeDemonstratedCount(Integer volumeDemonstratedCount) {
		this.volumeDemonstratedCount = volumeDemonstratedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.marking_train_count
	 * @return  the value of bo_train.marking_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getMarkingTrainCount() {
		return markingTrainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.marking_train_count
	 * @param markingTrainCount  the value for bo_train.marking_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setMarkingTrainCount(Integer markingTrainCount) {
		this.markingTrainCount = markingTrainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.introduction_lean_count
	 * @return  the value of bo_train.introduction_lean_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getIntroductionLeanCount() {
		return introductionLeanCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.introduction_lean_count
	 * @param introductionLeanCount  the value for bo_train.introduction_lean_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setIntroductionLeanCount(Integer introductionLeanCount) {
		this.introductionLeanCount = introductionLeanCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.student_parent_introduction_count
	 * @return  the value of bo_train.student_parent_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getStudentParentIntroductionCount() {
		return studentParentIntroductionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.student_parent_introduction_count
	 * @param studentParentIntroductionCount  the value for bo_train.student_parent_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setStudentParentIntroductionCount(Integer studentParentIntroductionCount) {
		this.studentParentIntroductionCount = studentParentIntroductionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.examination_train_count
	 * @return  the value of bo_train.examination_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getExaminationTrainCount() {
		return examinationTrainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.examination_train_count
	 * @param examinationTrainCount  the value for bo_train.examination_train_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setExaminationTrainCount(Integer examinationTrainCount) {
		this.examinationTrainCount = examinationTrainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.sop_process_explanation_count
	 * @return  the value of bo_train.sop_process_explanation_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getSopProcessExplanationCount() {
		return sopProcessExplanationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.sop_process_explanation_count
	 * @param sopProcessExplanationCount  the value for bo_train.sop_process_explanation_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setSopProcessExplanationCount(Integer sopProcessExplanationCount) {
		this.sopProcessExplanationCount = sopProcessExplanationCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.products_introduction_count
	 * @return  the value of bo_train.products_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getProductsIntroductionCount() {
		return productsIntroductionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.products_introduction_count
	 * @param productsIntroductionCount  the value for bo_train.products_introduction_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setProductsIntroductionCount(Integer productsIntroductionCount) {
		this.productsIntroductionCount = productsIntroductionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.operation_guidance_count
	 * @return  the value of bo_train.operation_guidance_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getOperationGuidanceCount() {
		return operationGuidanceCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.operation_guidance_count
	 * @param operationGuidanceCount  the value for bo_train.operation_guidance_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setOperationGuidanceCount(Integer operationGuidanceCount) {
		this.operationGuidanceCount = operationGuidanceCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.test_coach_count
	 * @return  the value of bo_train.test_coach_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Integer getTestCoachCount() {
		return testCoachCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.test_coach_count
	 * @param testCoachCount  the value for bo_train.test_coach_count
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setTestCoachCount(Integer testCoachCount) {
		this.testCoachCount = testCoachCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.create_by
	 * @return  the value of bo_train.create_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.create_by
	 * @param createBy  the value for bo_train.create_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.create_time
	 * @return  the value of bo_train.create_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.create_time
	 * @param createTime  the value for bo_train.create_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.update_by
	 * @return  the value of bo_train.update_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.update_by
	 * @param updateBy  the value for bo_train.update_by
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bo_train.update_time
	 * @return  the value of bo_train.update_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bo_train.update_time
	 * @param updateTime  the value for bo_train.update_time
	 * @mbggenerated  Mon Apr 17 08:47:27 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}