package com.jike.business.model;

import java.util.Date;

public class BoTrialReuslt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.trial_result_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Long trialResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.log_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.trial_result_detail
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private String trialResultDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.create_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.create_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.update_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_trial_reuslt.update_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.trial_result_id
     *
     * @return the value of bo_trial_reuslt.trial_result_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Long getTrialResultId() {
        return trialResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.trial_result_id
     *
     * @param trialResultId the value for bo_trial_reuslt.trial_result_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setTrialResultId(Long trialResultId) {
        this.trialResultId = trialResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.business_opportunity_id
     *
     * @return the value of bo_trial_reuslt.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_trial_reuslt.business_opportunity_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.log_id
     *
     * @return the value of bo_trial_reuslt.log_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.log_id
     *
     * @param logId the value for bo_trial_reuslt.log_id
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.trial_result_detail
     *
     * @return the value of bo_trial_reuslt.trial_result_detail
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public String getTrialResultDetail() {
        return trialResultDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.trial_result_detail
     *
     * @param trialResultDetail the value for bo_trial_reuslt.trial_result_detail
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setTrialResultDetail(String trialResultDetail) {
        this.trialResultDetail = trialResultDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.create_time
     *
     * @return the value of bo_trial_reuslt.create_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.create_time
     *
     * @param createTime the value for bo_trial_reuslt.create_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.create_by
     *
     * @return the value of bo_trial_reuslt.create_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.create_by
     *
     * @param createBy the value for bo_trial_reuslt.create_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.update_time
     *
     * @return the value of bo_trial_reuslt.update_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.update_time
     *
     * @param updateTime the value for bo_trial_reuslt.update_time
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_trial_reuslt.update_by
     *
     * @return the value of bo_trial_reuslt.update_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_trial_reuslt.update_by
     *
     * @param updateBy the value for bo_trial_reuslt.update_by
     *
     * @mbggenerated Mon Apr 10 15:51:57 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}