package com.jike.business.model;

import java.util.Date;

public class BoTrain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.bo_train_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Integer boTrainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.operation_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Integer operationTrainingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.correcting_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Integer correctingTrainingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_train.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.bo_train_id
     *
     * @return the value of bo_train.bo_train_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Integer getBoTrainId() {
        return boTrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.bo_train_id
     *
     * @param boTrainId the value for bo_train.bo_train_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setBoTrainId(Integer boTrainId) {
        this.boTrainId = boTrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.business_opportunity_id
     *
     * @return the value of bo_train.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.business_opportunity_id
     *
     * @param businessOpportunityId the value for bo_train.business_opportunity_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.log_id
     *
     * @return the value of bo_train.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.log_id
     *
     * @param logId the value for bo_train.log_id
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.operation_training_count
     *
     * @return the value of bo_train.operation_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Integer getOperationTrainingCount() {
        return operationTrainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.operation_training_count
     *
     * @param operationTrainingCount the value for bo_train.operation_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setOperationTrainingCount(Integer operationTrainingCount) {
        this.operationTrainingCount = operationTrainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.correcting_training_count
     *
     * @return the value of bo_train.correcting_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Integer getCorrectingTrainingCount() {
        return correctingTrainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.correcting_training_count
     *
     * @param correctingTrainingCount the value for bo_train.correcting_training_count
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setCorrectingTrainingCount(Integer correctingTrainingCount) {
        this.correctingTrainingCount = correctingTrainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.create_by
     *
     * @return the value of bo_train.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.create_by
     *
     * @param createBy the value for bo_train.create_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.create_time
     *
     * @return the value of bo_train.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.create_time
     *
     * @param createTime the value for bo_train.create_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.update_by
     *
     * @return the value of bo_train.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.update_by
     *
     * @param updateBy the value for bo_train.update_by
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_train.update_time
     *
     * @return the value of bo_train.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_train.update_time
     *
     * @param updateTime the value for bo_train.update_time
     *
     * @mbggenerated Tue Apr 11 09:44:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}