package com.jike.business.model;

import java.util.Date;

public class BusinessOpportunity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.business_opportunity_id
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.customer_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.business_opportunity_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String businessOpportunityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.business_opportunity_num
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String businessOpportunityNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.business_opportunity_type
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Integer businessOpportunityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.address_province
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String addressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.address_city
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String addressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.address_county
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String addressCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.address_detail
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.is_cancellation
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Integer isCancellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.business_opportunity_process
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private String businessOpportunityProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.create_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.update_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.create_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.update_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity.is_closed
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    private Integer isClosed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.business_opportunity_id
     *
     * @return the value of business_opportunity.business_opportunity_id
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.business_opportunity_id
     *
     * @param businessOpportunityId the value for business_opportunity.business_opportunity_id
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.customer_name
     *
     * @return the value of business_opportunity.customer_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.customer_name
     *
     * @param customerName the value for business_opportunity.customer_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.business_opportunity_name
     *
     * @return the value of business_opportunity.business_opportunity_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getBusinessOpportunityName() {
        return businessOpportunityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.business_opportunity_name
     *
     * @param businessOpportunityName the value for business_opportunity.business_opportunity_name
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setBusinessOpportunityName(String businessOpportunityName) {
        this.businessOpportunityName = businessOpportunityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.business_opportunity_num
     *
     * @return the value of business_opportunity.business_opportunity_num
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getBusinessOpportunityNum() {
        return businessOpportunityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.business_opportunity_num
     *
     * @param businessOpportunityNum the value for business_opportunity.business_opportunity_num
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setBusinessOpportunityNum(String businessOpportunityNum) {
        this.businessOpportunityNum = businessOpportunityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.business_opportunity_type
     *
     * @return the value of business_opportunity.business_opportunity_type
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Integer getBusinessOpportunityType() {
        return businessOpportunityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.business_opportunity_type
     *
     * @param businessOpportunityType the value for business_opportunity.business_opportunity_type
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setBusinessOpportunityType(Integer businessOpportunityType) {
        this.businessOpportunityType = businessOpportunityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.address_province
     *
     * @return the value of business_opportunity.address_province
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getAddressProvince() {
        return addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.address_province
     *
     * @param addressProvince the value for business_opportunity.address_province
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.address_city
     *
     * @return the value of business_opportunity.address_city
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.address_city
     *
     * @param addressCity the value for business_opportunity.address_city
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.address_county
     *
     * @return the value of business_opportunity.address_county
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getAddressCounty() {
        return addressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.address_county
     *
     * @param addressCounty the value for business_opportunity.address_county
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setAddressCounty(String addressCounty) {
        this.addressCounty = addressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.address_detail
     *
     * @return the value of business_opportunity.address_detail
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.address_detail
     *
     * @param addressDetail the value for business_opportunity.address_detail
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.is_cancellation
     *
     * @return the value of business_opportunity.is_cancellation
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Integer getIsCancellation() {
        return isCancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.is_cancellation
     *
     * @param isCancellation the value for business_opportunity.is_cancellation
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setIsCancellation(Integer isCancellation) {
        this.isCancellation = isCancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.business_opportunity_process
     *
     * @return the value of business_opportunity.business_opportunity_process
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public String getBusinessOpportunityProcess() {
        return businessOpportunityProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.business_opportunity_process
     *
     * @param businessOpportunityProcess the value for business_opportunity.business_opportunity_process
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setBusinessOpportunityProcess(String businessOpportunityProcess) {
        this.businessOpportunityProcess = businessOpportunityProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.create_time
     *
     * @return the value of business_opportunity.create_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.create_time
     *
     * @param createTime the value for business_opportunity.create_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.update_time
     *
     * @return the value of business_opportunity.update_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.update_time
     *
     * @param updateTime the value for business_opportunity.update_time
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.create_by
     *
     * @return the value of business_opportunity.create_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.create_by
     *
     * @param createBy the value for business_opportunity.create_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.update_by
     *
     * @return the value of business_opportunity.update_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.update_by
     *
     * @param updateBy the value for business_opportunity.update_by
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity.is_closed
     *
     * @return the value of business_opportunity.is_closed
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public Integer getIsClosed() {
        return isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity.is_closed
     *
     * @param isClosed the value for business_opportunity.is_closed
     *
     * @mbggenerated Wed Apr 05 13:53:33 CST 2017
     */
    public void setIsClosed(Integer isClosed) {
        this.isClosed = isClosed;
    }
}