package com.jike.business.model;

import java.util.Date;

public class BusinessOpportunityLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.log_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.detail_fee_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long detailFeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.happen_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Date happenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.business_opportunity_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.event_type
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.specific_event
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private String specificEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.working_hours
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long workingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.internal_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private String internalParticipant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.external_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private String externalParticipant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.create_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.create_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.update_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_opportunity_log.update_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.log_id
     *
     * @return the value of business_opportunity_log.log_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.log_id
     *
     * @param logId the value for business_opportunity_log.log_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.detail_fee_id
     *
     * @return the value of business_opportunity_log.detail_fee_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getDetailFeeId() {
        return detailFeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.detail_fee_id
     *
     * @param detailFeeId the value for business_opportunity_log.detail_fee_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setDetailFeeId(Long detailFeeId) {
        this.detailFeeId = detailFeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.happen_time
     *
     * @return the value of business_opportunity_log.happen_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Date getHappenTime() {
        return happenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.happen_time
     *
     * @param happenTime the value for business_opportunity_log.happen_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setHappenTime(Date happenTime) {
        this.happenTime = happenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.business_opportunity_id
     *
     * @return the value of business_opportunity_log.business_opportunity_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.business_opportunity_id
     *
     * @param businessOpportunityId the value for business_opportunity_log.business_opportunity_id
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.event_type
     *
     * @return the value of business_opportunity_log.event_type
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.event_type
     *
     * @param eventType the value for business_opportunity_log.event_type
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.specific_event
     *
     * @return the value of business_opportunity_log.specific_event
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public String getSpecificEvent() {
        return specificEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.specific_event
     *
     * @param specificEvent the value for business_opportunity_log.specific_event
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setSpecificEvent(String specificEvent) {
        this.specificEvent = specificEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.working_hours
     *
     * @return the value of business_opportunity_log.working_hours
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getWorkingHours() {
        return workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.working_hours
     *
     * @param workingHours the value for business_opportunity_log.working_hours
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setWorkingHours(Long workingHours) {
        this.workingHours = workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.internal_participant
     *
     * @return the value of business_opportunity_log.internal_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public String getInternalParticipant() {
        return internalParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.internal_participant
     *
     * @param internalParticipant the value for business_opportunity_log.internal_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setInternalParticipant(String internalParticipant) {
        this.internalParticipant = internalParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.external_participant
     *
     * @return the value of business_opportunity_log.external_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public String getExternalParticipant() {
        return externalParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.external_participant
     *
     * @param externalParticipant the value for business_opportunity_log.external_participant
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setExternalParticipant(String externalParticipant) {
        this.externalParticipant = externalParticipant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.create_time
     *
     * @return the value of business_opportunity_log.create_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.create_time
     *
     * @param createTime the value for business_opportunity_log.create_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.create_by
     *
     * @return the value of business_opportunity_log.create_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.create_by
     *
     * @param createBy the value for business_opportunity_log.create_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.update_time
     *
     * @return the value of business_opportunity_log.update_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.update_time
     *
     * @param updateTime the value for business_opportunity_log.update_time
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_opportunity_log.update_by
     *
     * @return the value of business_opportunity_log.update_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_opportunity_log.update_by
     *
     * @param updateBy the value for business_opportunity_log.update_by
     *
     * @mbggenerated Thu Apr 06 12:16:12 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}