package com.jike.business.model;

public class CityAreaCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_area_code.id
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_area_code.num
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_area_code.city
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_area_code.province
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_area_code.id
     *
     * @return the value of city_area_code.id
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_area_code.id
     *
     * @param id the value for city_area_code.id
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_area_code.num
     *
     * @return the value of city_area_code.num
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_area_code.num
     *
     * @param num the value for city_area_code.num
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_area_code.city
     *
     * @return the value of city_area_code.city
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_area_code.city
     *
     * @param city the value for city_area_code.city
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_area_code.province
     *
     * @return the value of city_area_code.province
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_area_code.province
     *
     * @param province the value for city_area_code.province
     *
     * @mbggenerated Tue Apr 18 10:45:08 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }
}