package com.jike.business.model;

import java.math.BigDecimal;
import java.util.Date;

public class CooperationDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.cooperation_details_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Long cooperationDetailsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.visit_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Long visitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.cooperation_mode
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private String cooperationMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.registered_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private BigDecimal registeredCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.education_case
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private String educationCase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.service_personnel_quantity
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Integer servicePersonnelQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.start_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private BigDecimal startCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.create_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.create_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.update_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cooperation_details.update_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.cooperation_details_id
	 * @return  the value of cooperation_details.cooperation_details_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Long getCooperationDetailsId() {
		return cooperationDetailsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.cooperation_details_id
	 * @param cooperationDetailsId  the value for cooperation_details.cooperation_details_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setCooperationDetailsId(Long cooperationDetailsId) {
		this.cooperationDetailsId = cooperationDetailsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.visit_id
	 * @return  the value of cooperation_details.visit_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Long getVisitId() {
		return visitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.visit_id
	 * @param visitId  the value for cooperation_details.visit_id
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.cooperation_mode
	 * @return  the value of cooperation_details.cooperation_mode
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public String getCooperationMode() {
		return cooperationMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.cooperation_mode
	 * @param cooperationMode  the value for cooperation_details.cooperation_mode
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setCooperationMode(String cooperationMode) {
		this.cooperationMode = cooperationMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.registered_capital
	 * @return  the value of cooperation_details.registered_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public BigDecimal getRegisteredCapital() {
		return registeredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.registered_capital
	 * @param registeredCapital  the value for cooperation_details.registered_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setRegisteredCapital(BigDecimal registeredCapital) {
		this.registeredCapital = registeredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.education_case
	 * @return  the value of cooperation_details.education_case
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public String getEducationCase() {
		return educationCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.education_case
	 * @param educationCase  the value for cooperation_details.education_case
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setEducationCase(String educationCase) {
		this.educationCase = educationCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.service_personnel_quantity
	 * @return  the value of cooperation_details.service_personnel_quantity
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Integer getServicePersonnelQuantity() {
		return servicePersonnelQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.service_personnel_quantity
	 * @param servicePersonnelQuantity  the value for cooperation_details.service_personnel_quantity
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setServicePersonnelQuantity(Integer servicePersonnelQuantity) {
		this.servicePersonnelQuantity = servicePersonnelQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.start_capital
	 * @return  the value of cooperation_details.start_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public BigDecimal getStartCapital() {
		return startCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.start_capital
	 * @param startCapital  the value for cooperation_details.start_capital
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setStartCapital(BigDecimal startCapital) {
		this.startCapital = startCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.create_by
	 * @return  the value of cooperation_details.create_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.create_by
	 * @param createBy  the value for cooperation_details.create_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.create_time
	 * @return  the value of cooperation_details.create_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.create_time
	 * @param createTime  the value for cooperation_details.create_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.update_by
	 * @return  the value of cooperation_details.update_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.update_by
	 * @param updateBy  the value for cooperation_details.update_by
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cooperation_details.update_time
	 * @return  the value of cooperation_details.update_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cooperation_details.update_time
	 * @param updateTime  the value for cooperation_details.update_time
	 * @mbggenerated  Thu Apr 13 08:17:51 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}