package com.jike.business.model;

import java.util.Date;

public class CooperativePartnerSchoolServiceLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.cps_service_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long cpsServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long cooperativePartnerSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.service_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.service_phone
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String servicePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_service_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.cps_service_id
     *
     * @return the value of cooperative_partner_school_service_log.cps_service_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getCpsServiceId() {
        return cpsServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.cps_service_id
     *
     * @param cpsServiceId the value for cooperative_partner_school_service_log.cps_service_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCpsServiceId(Long cpsServiceId) {
        this.cpsServiceId = cpsServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.cooperative_partner_school_id
     *
     * @return the value of cooperative_partner_school_service_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getCooperativePartnerSchoolId() {
        return cooperativePartnerSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.cooperative_partner_school_id
     *
     * @param cooperativePartnerSchoolId the value for cooperative_partner_school_service_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCooperativePartnerSchoolId(Long cooperativePartnerSchoolId) {
        this.cooperativePartnerSchoolId = cooperativePartnerSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.service_name
     *
     * @return the value of cooperative_partner_school_service_log.service_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.service_name
     *
     * @param serviceName the value for cooperative_partner_school_service_log.service_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.service_phone
     *
     * @return the value of cooperative_partner_school_service_log.service_phone
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getServicePhone() {
        return servicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.service_phone
     *
     * @param servicePhone the value for cooperative_partner_school_service_log.service_phone
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setServicePhone(String servicePhone) {
        this.servicePhone = servicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.create_by
     *
     * @return the value of cooperative_partner_school_service_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.create_by
     *
     * @param createBy the value for cooperative_partner_school_service_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.create_time
     *
     * @return the value of cooperative_partner_school_service_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.create_time
     *
     * @param createTime the value for cooperative_partner_school_service_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.update_by
     *
     * @return the value of cooperative_partner_school_service_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.update_by
     *
     * @param updateBy the value for cooperative_partner_school_service_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_service_log.update_time
     *
     * @return the value of cooperative_partner_school_service_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_service_log.update_time
     *
     * @param updateTime the value for cooperative_partner_school_service_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}