package com.jike.business.model;

import java.util.Date;

public class CooperativePartnerSchoolLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long cooperativePartnerSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.business_opportunity_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long businessOpportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.school_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.address_province
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String addressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.address_city
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String addressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.address_country
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String addressCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.address_detail
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.school_scale
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String schoolScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.school_level
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String schoolLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.school_property
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Integer schoolProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.school_category
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private String schoolCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_partner_school_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.cooperative_partner_school_id
     *
     * @return the value of cooperative_partner_school_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getCooperativePartnerSchoolId() {
        return cooperativePartnerSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.cooperative_partner_school_id
     *
     * @param cooperativePartnerSchoolId the value for cooperative_partner_school_log.cooperative_partner_school_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCooperativePartnerSchoolId(Long cooperativePartnerSchoolId) {
        this.cooperativePartnerSchoolId = cooperativePartnerSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.business_opportunity_id
     *
     * @return the value of cooperative_partner_school_log.business_opportunity_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getBusinessOpportunityId() {
        return businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.business_opportunity_id
     *
     * @param businessOpportunityId the value for cooperative_partner_school_log.business_opportunity_id
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setBusinessOpportunityId(Long businessOpportunityId) {
        this.businessOpportunityId = businessOpportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.school_name
     *
     * @return the value of cooperative_partner_school_log.school_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.school_name
     *
     * @param schoolName the value for cooperative_partner_school_log.school_name
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.address_province
     *
     * @return the value of cooperative_partner_school_log.address_province
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getAddressProvince() {
        return addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.address_province
     *
     * @param addressProvince the value for cooperative_partner_school_log.address_province
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.address_city
     *
     * @return the value of cooperative_partner_school_log.address_city
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.address_city
     *
     * @param addressCity the value for cooperative_partner_school_log.address_city
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.address_country
     *
     * @return the value of cooperative_partner_school_log.address_country
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getAddressCountry() {
        return addressCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.address_country
     *
     * @param addressCountry the value for cooperative_partner_school_log.address_country
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setAddressCountry(String addressCountry) {
        this.addressCountry = addressCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.address_detail
     *
     * @return the value of cooperative_partner_school_log.address_detail
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.address_detail
     *
     * @param addressDetail the value for cooperative_partner_school_log.address_detail
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.school_scale
     *
     * @return the value of cooperative_partner_school_log.school_scale
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getSchoolScale() {
        return schoolScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.school_scale
     *
     * @param schoolScale the value for cooperative_partner_school_log.school_scale
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setSchoolScale(String schoolScale) {
        this.schoolScale = schoolScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.school_level
     *
     * @return the value of cooperative_partner_school_log.school_level
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getSchoolLevel() {
        return schoolLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.school_level
     *
     * @param schoolLevel the value for cooperative_partner_school_log.school_level
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setSchoolLevel(String schoolLevel) {
        this.schoolLevel = schoolLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.school_property
     *
     * @return the value of cooperative_partner_school_log.school_property
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Integer getSchoolProperty() {
        return schoolProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.school_property
     *
     * @param schoolProperty the value for cooperative_partner_school_log.school_property
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setSchoolProperty(Integer schoolProperty) {
        this.schoolProperty = schoolProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.school_category
     *
     * @return the value of cooperative_partner_school_log.school_category
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public String getSchoolCategory() {
        return schoolCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.school_category
     *
     * @param schoolCategory the value for cooperative_partner_school_log.school_category
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setSchoolCategory(String schoolCategory) {
        this.schoolCategory = schoolCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.create_by
     *
     * @return the value of cooperative_partner_school_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.create_by
     *
     * @param createBy the value for cooperative_partner_school_log.create_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.create_time
     *
     * @return the value of cooperative_partner_school_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.create_time
     *
     * @param createTime the value for cooperative_partner_school_log.create_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.update_by
     *
     * @return the value of cooperative_partner_school_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.update_by
     *
     * @param updateBy the value for cooperative_partner_school_log.update_by
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_partner_school_log.update_time
     *
     * @return the value of cooperative_partner_school_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_partner_school_log.update_time
     *
     * @param updateTime the value for cooperative_partner_school_log.update_time
     *
     * @mbggenerated Fri May 19 09:09:19 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}