package com.jike.business.model;

import java.util.Date;

public class DailyEvents {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.daily_events_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Long dailyEventsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.log_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.daily_events_detail
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private String dailyEventsDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.create_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.create_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.update_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_events.update_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.daily_events_id
     *
     * @return the value of daily_events.daily_events_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Long getDailyEventsId() {
        return dailyEventsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.daily_events_id
     *
     * @param dailyEventsId the value for daily_events.daily_events_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setDailyEventsId(Long dailyEventsId) {
        this.dailyEventsId = dailyEventsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.log_id
     *
     * @return the value of daily_events.log_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.log_id
     *
     * @param logId the value for daily_events.log_id
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.daily_events_detail
     *
     * @return the value of daily_events.daily_events_detail
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public String getDailyEventsDetail() {
        return dailyEventsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.daily_events_detail
     *
     * @param dailyEventsDetail the value for daily_events.daily_events_detail
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setDailyEventsDetail(String dailyEventsDetail) {
        this.dailyEventsDetail = dailyEventsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.create_time
     *
     * @return the value of daily_events.create_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.create_time
     *
     * @param createTime the value for daily_events.create_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.create_by
     *
     * @return the value of daily_events.create_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.create_by
     *
     * @param createBy the value for daily_events.create_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.update_time
     *
     * @return the value of daily_events.update_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.update_time
     *
     * @param updateTime the value for daily_events.update_time
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_events.update_by
     *
     * @return the value of daily_events.update_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_events.update_by
     *
     * @param updateBy the value for daily_events.update_by
     *
     * @mbggenerated Mon Apr 10 18:57:09 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}