package com.jike.business.model;

import java.util.Date;

public class PartnerAgentArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.partner_agent_area_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Long partnerAgentAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.sign_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Long signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.address_province
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private String addressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.address_city
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private String addressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.address_county
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private String addressCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.create_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.create_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.update_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_agent_area.update_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.partner_agent_area_id
     *
     * @return the value of partner_agent_area.partner_agent_area_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Long getPartnerAgentAreaId() {
        return partnerAgentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.partner_agent_area_id
     *
     * @param partnerAgentAreaId the value for partner_agent_area.partner_agent_area_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setPartnerAgentAreaId(Long partnerAgentAreaId) {
        this.partnerAgentAreaId = partnerAgentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.sign_id
     *
     * @return the value of partner_agent_area.sign_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.sign_id
     *
     * @param signId the value for partner_agent_area.sign_id
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.address_province
     *
     * @return the value of partner_agent_area.address_province
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public String getAddressProvince() {
        return addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.address_province
     *
     * @param addressProvince the value for partner_agent_area.address_province
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.address_city
     *
     * @return the value of partner_agent_area.address_city
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.address_city
     *
     * @param addressCity the value for partner_agent_area.address_city
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.address_county
     *
     * @return the value of partner_agent_area.address_county
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public String getAddressCounty() {
        return addressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.address_county
     *
     * @param addressCounty the value for partner_agent_area.address_county
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setAddressCounty(String addressCounty) {
        this.addressCounty = addressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.create_time
     *
     * @return the value of partner_agent_area.create_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.create_time
     *
     * @param createTime the value for partner_agent_area.create_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.create_by
     *
     * @return the value of partner_agent_area.create_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.create_by
     *
     * @param createBy the value for partner_agent_area.create_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.update_time
     *
     * @return the value of partner_agent_area.update_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.update_time
     *
     * @param updateTime the value for partner_agent_area.update_time
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_agent_area.update_by
     *
     * @return the value of partner_agent_area.update_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_agent_area.update_by
     *
     * @param updateBy the value for partner_agent_area.update_by
     *
     * @mbggenerated Thu Apr 13 10:14:44 CST 2017
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}